### ISSUE TITLE
NullPointerException in BackgroundTask.java file

### ISSUE THREAD

**Issue by mohangandhiGH** [CUTR-at-USF/gtfs-realtime-validator#110]
**Summary:** 

The results received after validation in `BackgroundTask` should be first checked for `null` value and then added to database if not null. There is a minor reordering of lines in below code needs to be done such that `!=null` condition is checked first.
```
for (ErrorListHelperModel errorList : errorLists) {
      if (errorList != null && !errorList.getOccurrenceList().isEmpty()) {
```

**Steps to reproduce:** 

Run the application. If errorList received in `BackgroundTask.java` contains a null value, it will through a null pointer exception. 
Here is the stack trace
```
java.lang.NullPointerException
	at edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask.validateEntity(BackgroundTask.java:207)
	at edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask.run(BackgroundTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Expected behavior:** 

Should not through any exception. 

**Observed behavior:** 

Throwing a null pointer exception.

**Platform:** 

Windows 10 Home, jdk1.8.0_73 and Chrome

**Comment by barbeau** [comment]
So I think it should actually check if errorList.getOccurrenceList() is null, not errorList, right?

**Comment by mohangandhiGH** [comment]
@barbeau I beleive it should check `if(errorLists != null)` first before coming to for loop.
