### ISSUE TITLE
QueryTest error with java.sql.SQLIntegrityConstraintViolationException

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#151]
**Summary:** 

When running the unit tests with the current `master` branch, I'm seeing an error in `QueryTest.setUp()`:

~~~
[main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
[main] WARN org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-configuration. Use namespace http://www.hibernate.org/dtd/hibernate-configuration instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
[main] WARN org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator - HHH000022: c3p0 properties were encountered, but the c3p0 provider class was not found on the classpath; these properties are going to be ignored.
[main] WARN org.hibernate.orm.connections.pooling - HHH10001002: Using Hibernate built-in connection pool (not for production use!)
org.hibernate.NonUniqueObjectException: A different object with the same identifier value was already associated with the session : [edu.usf.cutr.gtfsrtvalidator.api.model.ValidationRule#W005]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:169)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:192)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:177)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:97)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:73)
	at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:642)
	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:634)
	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:629)
	at edu.usf.cutr.gtfsrtvalidator.db.GTFSDB.InitializeDB(GTFSDB.java:63)
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest.setUp(GtfsFeedTest.java:41)
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
[main] INFO edu.usf.cutr.gtfsrtvalidator.db.GTFSDB - Table initialized successfully
java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: foreign key no parent; FK9Y5KQQU1LEH3T58XD3EUNA12J table: MESSAGELOG
~~~

This started failing with https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/51a4d5f7ee63a4beb7f4ff03b671bdc29c55244c, so I believe it's been triggered by another one of the unit tests inserting a conflicting record in the database.

@mohangandhiGH Could you please take a look at this?

**Steps to reproduce:** 

Run `mvn test` (or just run `QueryTest` in IntelliJ)

**Expected behavior:** 

Unit tests should pass

**Observed behavior:** 

`QueryTest` unit test errors out

**Platform:** 

Windows 7 Enterprise with jdk1.8.0_73

**Comment by barbeau** [comment]
@mohangandhiGH Actually, looks like this was my mistake in https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/51a4d5f7ee63a4beb7f4ff03b671bdc29c55244c (I missed an edit in a copy/paste) - I'll go ahead and fix this.
