### ISSUE TITLE
Some tests broken due to empty results sets

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#166]
**Summary:** 

While working on #164 in https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/295c21887531f92f7c20c31ec0d9896862688d82, I realized that our `TestUtils.assertResults()` method was allowing empty result sets in the situation when we expected errors to return, which resulted in code erroneously passing unit tests which should have failed.

I added an `IllegalArgumentException` to `TestUtils.assertResults()` in https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/295c21887531f92f7c20c31ec0d9896862688d82 to catch these problems, which has now (correctly) resulted in a few unit tests that are throwing this exception - we need to fix these.

Here's an example of the output we now see:

~~~
java.lang.IllegalArgumentException: If at least one error is expected results cannot be empty

	at edu.usf.cutr.gtfsrtvalidator.test.util.TestUtils.assertResults(TestUtils.java:44)
	at edu.usf.cutr.gtfsrtvalidator.test.headerandentity.TimestampValidationTest.testTimestampValidationE001(TimestampValidationTest.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
~~~

**Steps to reproduce:** 

Run all unit tests

**Expected behavior:** 

They should all pass

**Observed behavior:** 

A few are now throwing `IllegalArgumentExceptions`

**Comment by barbeau** [comment]
I'm working on this.
