### ISSUE TITLE
OOM running tests when trying to build master

### ISSUE THREAD

**Issue by laidig** [CUTR-at-USF/gtfs-realtime-validator#212]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:** 

Run with no mvn or java opts set as environment variables 

**Expected behavior:** 

Package jar

**Observed behavior:** 

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 264.188 sec <<< FAILURE! - in edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest
testGtfsFeed(edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest)  Time elapsed: 260.368 sec  <<< ERROR!
java.lang.OutOfMemoryError: Java heap space
	at java.util.jar.Attributes.read(Attributes.java:394)
	at java.util.jar.Manifest.read(Manifest.java:199)
	at java.util.jar.Manifest.<init>(Manifest.java:69)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:199)
	at java.util.jar.JarFile.getManifest(JarFile.java:180)
	at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:981)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:49)
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.applySqlString(SchemaMigratorImpl.java:572)
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.applySqlStrings(SchemaMigratorImpl.java:595)
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.migrateTable(SchemaMigratorImpl.java:364)
	at 

**Platform:** 
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.8.0-49-generic", arch: "amd64", family: "unix"

**Comment by barbeau** [comment]
Thanks @laidig.  So you're seeing this when running `mvn package`?  Have you tried building project in IDE like [IntelliJ](https://www.jetbrains.com/idea/)?  Just curious as to what works on your machine.

**Comment by laidig** [comment]
@barbeau, that is correct. it was `mvn package` from the shell. 

Via IntelliJ, same problem.

**Comment by barbeau** [comment]
Interesting - so we have `-Xmx4G -Xms1G -Djava.awt.headless=true` in the `jvm.config` file, which I understand is supposed to be used by Maven.

If you manually specify these on the command line, does it build?  Are you able to tweak these numbers to get it to build?

**Comment by barbeau** [comment]
Looks like the test `https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/src/test/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeedTest.java` is causing the out of memory exception - this test loads a sample GTFS feed into the database.  A potential fix is to change to a smaller GTFS zip file, although HART's GTFS file which is currently used isn't that big.

If you change `validGtfsFeedURL` to `https://github.com/CUTR-at-USF/gtfs-realtime-validator/raw/master/src/test/resources/bullrunner-gtfs.zip` on Line 31 of this class, and run `mvn clean package`, does that fix it?

**Comment by barbeau** [comment]
Note to myself - according to https://stackoverflow.com/a/4074196/937715, the JVM arguments aren't passed to the JVM executing unit tests when using `maven-surefire-plugin`.

**Comment by barbeau** [comment]
@laidig Can you give the current master branch (including https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/714bcb44854dcf60fd55c2e7a6a64cf248f01834) a try?  I think this should be resolved now - I've included the -Xmx4G -Xms1G in the pom.xml config for `maven-surefire-plugin`, which I believe should solve the issue.  If it doesn't, please re-open.
