### ISSUE TITLE
W003 description doesn't match rule implementation

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#241]
**Summary:** 

Currently W003 is `VehiclePosition` and `TripUpdate` feed mismatch, which says:

>If separate Vehicle Positions and Trip Updates feeds are provided, `VehicleDescriptor` or `TripDescriptor` values should match between the two feeds.  

>In other words, if the `VehiclePosition` has a `vehicle_id` A that is assigned to `trip_id` 4, then the `TripUpdate` feed should have a prediction for `trip_id` 4 that includes a reference to `vehicle_id` A.

The current implementation of W003 actually checks that for each ID in the VehiclePosition feed, that same ID appears in TripUpdates, and vice versa.  If the ID is missing from the feed, it generates a warning.

This is different from checking for ID pair mismatches between the two feeds, which should be an error.

We should update the W003 warning description to reflect the missing ID check behavior, and add a new rule that checks for ID pair mismatches.

**Comment by barbeau** [comment]
I'm working on this

**Comment by barbeau** [comment]
Re-opening - when I run this on a real GTFS-rt feed, I see the following:

~~~
java.lang.IllegalArgumentException: value already present: 
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:115)
	at com.google.common.collect.AbstractBiMap.putInBothMaps(AbstractBiMap.java:112)
	at com.google.common.collect.AbstractBiMap.put(AbstractBiMap.java:96)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:85)
	at edu.usf.cutr.gtfsrtvalidator.validation.rules.CrossFeedDescriptorValidator.validate(CrossFeedDescriptorValidator.java:66)
	at edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask.validateEntity(BackgroundTask.java:219)
	at edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask.run(BackgroundTask.java:208)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
~~~

**Comment by barbeau** [comment]
The issue here is that HashBiMaps require that the value (in addition to the key) is unique, and we're currently mapping TripUpdate trip_ids without vehicle.ids to an empty string (and VehiclePosition vehicle.ids without trip_ids to an empty string).  So, if more than one trip doesn't have a vehicle_id, or more than one vehicle doesn't have a trip_id, they both map to an empty string, which causes the `IllegalArgumentException`.

For example, from MBTA's feed, a TripUpdate with an empty `vehicle` (so no `vehicle.id`):

~~~
    "time": 1499287153
            },
            "stop_id": "64"
          }
        ],
        "vehicle": {}
~~~
