### ISSUE TITLE
NPE on first feed iteration when monitoring multiple feeds

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#253]
**Summary:** 

When monitoring the MBTA VehiclePositions and TripUpdates feeds together, the first feed iteration generates a `NullPointerException`:

~~~
[main] INFO edu.usf.cutr.gtfsrtvalidator.db.GTFSDB - Table initialized successfully
[main] INFO edu.usf.cutr.gtfsrtvalidator.Main - Go to http://localhost:8080 in your browser
[qtp1663738275-31] INFO edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeed - Downloading GTFS data from http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip...
[qtp1663738275-31] INFO edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeed - GTFS data downloaded successfully
[qtp1663738275-31] INFO edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeed - GTFS URL already exists exists in database - checking if data has changed...
[qtp1663738275-31] INFO edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeed - GTFS data hasn't changed since last execution
[qtp1663738275-20] INFO edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsRtFeed - http://developer.mbta.com/lib/GTRTFS/Alerts/VehiclePositions.pb is a valid GTFS-realtime feed
[qtp1663738275-22] INFO edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsRtFeed - http://developer.mbta.com/lib/GTRTFS/Alerts/TripUpdates.pb is a valid GTFS-realtime feed
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.GtfsMetadata - Building GtfsMetadata for http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip...
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.GtfsMetadata - Processing trips and building trip shapes for http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip...
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.GtfsMetadata - Trips polylines processed for http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip in 4.287 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.GtfsMetadata - Repeated stop_ids for trips in stop_times.txt processed for http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip in 0.164 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.GtfsMetadata - Built GtfsMetadata for http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip in 4.879 seconds
java.lang.NullPointerException
	at edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask.run(BackgroundTask.java:185)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
~~~

This may be related to the changes introduced in https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/234.

**Steps to reproduce:** 

1. Start the validator
1. Enter the MBTA feeds (both VehiclePositions and TripUpdates) in the same session (i.e., click "Add Feed" to include both GTFS-rt feeds):
      * GTFS - http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip (~13.4MB)
      * TripUpdates - http://developer.mbta.com/lib/GTRTFS/Alerts/TripUpdates.pb (~8.6MB)
      * VehiclePositions - http://developer.mbta.com/lib/GTRTFS/Alerts/VehiclePositions.pb (~44KB)
1. Start monitoring

**Expected behavior:** 

Not generate an NPE

**Observed behavior:** 

Above NPE is thrown

**Platform:** 

Windows 7 Enterprise with jdk1.8.0_73 and Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by barbeau** [comment]
@Suryakandukoori I was reading up on Java Executors and Threads, and contrary to the end of our meeting on Friday I don’t think that BackgroundTask.mCurrentGtfsRtFeed needs to be ThreadLocal. It boils down to what happens when you pass the same Runnable instance into a constructor for a new Thread, and because we aren't modifying the value it should be OK as-is.
