### ISSUE TITLE
Validator becomes CPU bound after long running time

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#259]
**Summary:** 

When monitoring this feed:
* GTFS - https://gtfsrt.api.translink.com.au/GTFS/SEQ_GTFS.zip
* GTFS-rt - https://gtfsrt.api.translink.com.au/Feed/SEQ

...for around 3 hours and 30 min (running in IntelliJ in background on my machine), the time to process feeds became greater and greater, to the point where the tool seemed to become completely CPU bound and stuck in the middle of processing the `StopValidator` rule in the middle of an iteration.  When clicking on the last iteration ID in the web UI to try and view it, the page loading spinner keeps animating and the iteration data never loads:

![image](https://user-images.githubusercontent.com/928045/28792237-f0666c90-75fc-11e7-9e02-47d4f73e9f03.png)

Here is the log, which also seems to suffer from the issue of the times for each rule not adding up to the total processing time for the iteration (https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/196).  Note that some processing times are very large, and then they come back down.

~~~
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 10.577 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed CrossFeedDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed VehicleValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TimestampValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopTimeUpdateValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TripDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeZeroValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeOneValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed HeaderValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 30.407 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed CrossFeedDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed VehicleValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TimestampValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopTimeUpdateValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TripDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeZeroValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeOneValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed HeaderValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 988.669 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed CrossFeedDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed VehicleValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TimestampValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopTimeUpdateValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TripDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeZeroValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeOneValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed HeaderValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 126.964 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed CrossFeedDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed VehicleValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TimestampValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopTimeUpdateValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TripDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeZeroValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeOneValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed HeaderValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 30.399 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed CrossFeedDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed VehicleValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TimestampValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopTimeUpdateValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TripDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeZeroValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeOneValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed HeaderValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 30.276 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed CrossFeedDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed VehicleValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TimestampValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopTimeUpdateValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TripDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeZeroValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeOneValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed HeaderValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 30.392 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed CrossFeedDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed VehicleValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TimestampValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopTimeUpdateValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TripDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeZeroValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed FrequencyTypeOneValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed HeaderValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 86.93 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed CrossFeedDescriptorValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed VehicleValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TimestampValidator in 0.0 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed StopTimeUpdateValidator in 2.463 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - Processed TripDescriptorValidator in 0.0 seconds
~~~

Above line is where the tool froze for a long time (over 10 minutes) without anything changing.

**Steps to reproduce:** 

Not sure, but try starting the tool and monitoring this feed:
* GTFS - https://gtfsrt.api.translink.com.au/GTFS/SEQ_GTFS.zip
* GTFS-rt - https://gtfsrt.api.translink.com.au/Feed/SEQ

...within IntelliJ for over 3 hrs.

This was the only feed the tool was monitoring (i.e., there was only one `BackgroundTask` thread instance).  I did click on most recent iteration ID to see it in the tool (which resulted in the hanging page screenshot above).  I had another tab open for the 3+hrs to one of the first iterations recorded for the feed - not sure if this has anything to do with it.

This is using default HSQLDB configuration for data storage.

**Expected behavior:** 

Tool continues to operate like normal with processing times for each iteration below 5 seconds.

**Observed behavior:** 

Tool seems to become completely CPU bound in the middle of processing a rule and freezes.

**Platform:** 

Windows 10 Home w/ jdk1.8.0_112 64 bit and Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by barbeau** [comment]
Here's a screenshot of the Task Manager while the tool is stuck:

![image](https://user-images.githubusercontent.com/928045/28792589-1cf1d744-75fe-11e7-845f-6ac92c7510a4.png)

**Comment by barbeau** [comment]
I'm monitoring this again, and I'm getting exception on each iteration:

~~~
[pool-4-thread-1] DEBUG edu.usf.cutr.gtfsrtvalidator.validation.rules.TripDescriptorValidator - trip_id 9797456-BT 17_18-JUL_FUL-Weekday-01 does not have a schedule_relationship
[pool-4-thread-1] DEBUG edu.usf.cutr.gtfsrtvalidator.validation.rules.TripDescriptorValidator - trip_id 10007643-GCLR 17_18-GCLR2014-Weekday-02 stop_sequence 4 (and potentially more for this trip) does not have a schedule_relationship
[pool-4-thread-1] DEBUG edu.usf.cutr.gtfsrtvalidator.validation.rules.TripDescriptorValidator - trip_id 10007643-GCLR 17_18-GCLR2014-Weekday-02 does not have a schedule_relationship
java.lang.NullPointerException
	at edu.usf.cutr.gtfsrtvalidator.validation.rules.TripDescriptorValidator.checkE023(TripDescriptorValidator.java:287)
	at edu.usf.cutr.gtfsrtvalidator.validation.rules.TripDescriptorValidator.validate(TripDescriptorValidator.java:116)
	at edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask.validateEntity(BackgroundTask.java:224)
	at edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask.run(BackgroundTask.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
~~~

Looks like this terminates the thread running the rules as no more output is seen until the next iteration.

**Comment by barbeau** [comment]
The line causing the exception is:

`int firstArrivalTime = gtfsMetadata.getTripStopTimes().get(tripId).get(0).getArrivalTime();`

Here's the entire code block (with the `// <--...` comment added by me to point out the line causing the exception):

~~~
    /**
     * Checks rule E023 - "start_time does not match GTFS initial arrival_time", and adds any errors that are found to the provided error list
     *
     * @param entity The VehiclePosition or TripUpdate that contains the data to be evaluated for rule E023
     * @param trip   The TripDescriptor be evaluated for rule E023
     * @param errors list to add any errors for E023 to
     */
    private void checkE023(Object entity, GtfsRealtime.TripDescriptor trip, GtfsMetadata gtfsMetadata, List<OccurrenceModel> errors) {
        String startTime = trip.getStartTime();
        String tripId = trip.getTripId();
        if (tripId != null && !gtfsMetadata.getExactTimesZeroTripIds().contains(tripId) && !gtfsMetadata.getExactTimesOneTrips().containsKey(tripId)) {
            // Trip is a normal (not frequencies.txt) trip
            int firstArrivalTime = gtfsMetadata.getTripStopTimes().get(tripId).get(0).getArrivalTime(); // <--- NPE is thrown here
            String formattedArrivalTime = TimestampUtils.secondsAfterMidnightToClock(firstArrivalTime);
            if (!startTime.equals(formattedArrivalTime)) {
                String prefix = "GTFS-rt " + getVehicleAndTripIdText(entity) + " start_time is " + startTime + " and GTFS initial arrival_time is " + formattedArrivalTime;
                RuleUtils.addOccurrence(E023, prefix, errors, _log);
            }
        }
    }
~~~

**Comment by barbeau** [comment]
NPE issue opened at checkE020, and that issue is fixed via https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/54241f39ef3d4deabf4a87e5fc7dd3a83b839cbe.

**Comment by barbeau** [comment]
I does look like there is some bottleneck in `TripDescriptorValidator` rule execution - after adding more benchmarking log statements as part of #226, here's what I see in the log:

~~~
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
Processed gtfsRtFeedUrl.openStream() for https://gtfsrt.api.translink.com.au/Feed/SEQ in 0.676 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
Processed IOUtils.toByteArray(in) for https://gtfsrt.api.translink.com.au/Feed/SEQ in 1.527 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
Processed Protobuf decode for https://gtfsrt.api.translink.com.au/Feed/SEQ in 0.003 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
CrossFeedDescriptorValidator - rule = 0.0 seconds, database = 0.0 seconds
VehicleValidator - rule = 0.031 seconds, database = 0.002 seconds
TimestampValidator - rule = 0.019 seconds, database = 0.011 seconds
StopTimeUpdateValidator - rule = 0.013 seconds, database = 0.02 seconds
TripDescriptorValidator - rule = 4.437 seconds, database = 0.048 seconds  <-- Processing took 4.437 seconds!!!
StopValidator - rule = 0.005 seconds, database = 0.002 seconds
FrequencyTypeZeroValidator - rule = 0.0 seconds, database = 0.0 seconds
FrequencyTypeOneValidator - rule = 0.0 seconds, database = 0.0 seconds
HeaderValidator - rule = 0.0 seconds, database = 0.0 seconds
Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 6.824 seconds
~~~

The interesting part is `TripDescriptorValidator - rule = 4.437 seconds`.  Looks like we need to benchmark  `TripDescriptorValidator` further to see where it's getting hung up.

**Comment by barbeau** [comment]
`TripDescriptorValidator` doesn't always get hung up - here's a later iteration where it's only 0.004 seconds:

~~~
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
Processed gtfsRtFeedUrl.openStream() for https://gtfsrt.api.translink.com.au/Feed/SEQ in 0.301 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
Processed IOUtils.toByteArray(in) for https://gtfsrt.api.translink.com.au/Feed/SEQ in 1.494 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
Processed Protobuf decode for https://gtfsrt.api.translink.com.au/Feed/SEQ in 0.004 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
Processed gtfsRtFeedUrl.openStream() for https://gtfsrt.api.translink.com.au/Feed/SEQ in 0.309 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
Processed IOUtils.toByteArray(in) for https://gtfsrt.api.translink.com.au/Feed/SEQ in 2.376 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
Processed Protobuf decode for https://gtfsrt.api.translink.com.au/Feed/SEQ in 0.004 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
CrossFeedDescriptorValidator - rule = 0.0 seconds, database = 0.0 seconds
VehicleValidator - rule = 0.02 seconds, database = 0.001 seconds
TimestampValidator - rule = 0.011 seconds, database = 0.009 seconds
StopTimeUpdateValidator - rule = 0.011 seconds, database = 0.016 seconds
TripDescriptorValidator - rule = 0.004 seconds, database = 0.031 seconds
StopValidator - rule = 0.004 seconds, database = 0.001 seconds
FrequencyTypeZeroValidator - rule = 0.0 seconds, database = 0.0 seconds
FrequencyTypeOneValidator - rule = 0.0 seconds, database = 0.0 seconds
HeaderValidator - rule = 0.0 seconds, database = 0.0 seconds
Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 2.82 seconds
~~~

**Comment by barbeau** [comment]
Related - good evaluation of different Java hash map implementations:
http://java-performance.info/hashmap-overview-jdk-fastutil-goldman-sachs-hppc-koloboke-trove-january-2015/

**Comment by barbeau** [comment]
In newer tests (master branch at https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/574a2b8d8ab353cf306e5adb6aae659ea7106b3e) with "ignore shapes" command line/ web UI turned on (batch process and webapp), on both archived and real-time SEQ data, it seems the main bottleneck now is in the HSQL database:

~~~
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
https://gtfsrt.api.translink.com.au/Feed/SEQ gtfsRtFeedUrl.openStream() in 2.174 seconds
https://gtfsrt.api.translink.com.au/Feed/SEQ IOUtils.toByteArray(in) in 0.008 seconds
https://gtfsrt.api.translink.com.au/Feed/SEQ protobuf decode in 0.001 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
CrossFeedDescriptorValidator - rule = 0.0 seconds, database = 0.898 seconds
VehicleValidator - rule = 1.71 seconds, database = 170.15 seconds
TimestampValidator - rule = 0.005 seconds, database = 134.89 seconds
StopTimeUpdateValidator - rule = 0.004 seconds, database = 23.538 seconds
TripDescriptorValidator - rule = 0.001 seconds, database = 160.697 seconds
StopValidator - rule = 0.001 seconds, database = 0.0 seconds
FrequencyTypeZeroValidator - rule = 0.0 seconds, database = 0.0 seconds
FrequencyTypeOneValidator - rule = 0.0 seconds, database = 0.0 seconds
HeaderValidator - rule = 0.0 seconds, database = 0.0 seconds
Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 494.147 seconds
---------------------
~~~

I can't reproduce the delay within the rule again with "ignore shapes" turned on.  When "ignore shapes" is turned off and using the batch processor, there is definitely a delay in `VehicleValidator` due to the spatial queries for point within buffer of trip:

~~~
---------------------
[main] INFO edu.usf.cutr.gtfsrtvalidator.lib.batch.BatchProcessor - Read 3254326352417162.StopTimeUpdateValidator to byte array in 0.016 seconds
[main] INFO edu.usf.cutr.gtfsrtvalidator.lib.batch.BatchProcessor - Decoded 3254326352417162.StopTimeUpdateValidator protobuf in 0.029 seconds
[main] INFO edu.usf.cutr.gtfsrtvalidator.lib.batch.BatchProcessor - 
CrossFeedDescriptorValidator - rule = 0.008 seconds
VehicleValidator - rule = 17.421 seconds
TimestampValidator - rule = 2.676 seconds
StopTimeUpdateValidator - rule = 0.101 seconds
TripDescriptorValidator - rule = 0.063 seconds
StopValidator - rule = 0.057 seconds
FrequencyTypeZeroValidator - rule = 0.001 seconds
FrequencyTypeOneValidator - rule = 0.001 seconds
HeaderValidator - rule = 0.0 seconds
Processed 3254326352417162.StopTimeUpdateValidator in 20.39 seconds
~~~

...but I don't see any extremely large delays in the other rule implementations.

Note that this feed is pretty huge - I'm seeing 2539 entities (TripUpdates and VehiclePositions) in the feed from a GTFS-rt file I archived a few weeks ago.

I'm going to close this for now - I'll re-open if I can reproduce the issue again within a rule.  

Note that running the tool with a dedicated RDMS (e.g., MySQL, MS SQL Server) should improve database performance significantly (see https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/308 for our WIP setup of a stable hosted instance).
