### ISSUE TITLE
HsqlException - string truncation table: OCCURRENCE column: PREFIX for RATP data

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#289]
**Summary:** 

I currently get this exception if I run the validator in normal server mode for RATP's feeds:
* GTFS - http://ratp.spiralo.net/stif_gtfs_enhanced_rer_latest.zip
* GTFS-realtime Trip Updates - http://stif.spiralo.net/STIF

~~~
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.GtfsMetadata - Built GtfsMetadata for http://ratp.spiralo.net/stif_gtfs_enhanced_rer_latest.zip in 5.563 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
http://stif.spiralo.net/STIF gtfsRtFeedUrl.openStream() in 0.783 seconds
http://stif.spiralo.net/STIF IOUtils.toByteArray(in) in 0.453 seconds
http://stif.spiralo.net/STIF protobuf decode in 0.011 seconds
[pool-4-thread-1] WARN org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 3401, SQLState: 22001
[pool-4-thread-1] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - data exception: string data, right truncation;  table: OCCURRENCE column: PREFIX
org.hibernate.exception.DataException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:52)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
	at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:57)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:42)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2840)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3411)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:619)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:273)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:254)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:299)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:192)
	at org.hibernate.event.internal.DefaultSaveEventListener.saveWithGeneratedOrRequestedId(DefaultSaveEventListener.java:38)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:177)
	at org.hibernate.event.internal.DefaultSaveEventListener.performSaveOrUpdate(DefaultSaveEventListener.java:32)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:73)
	at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:673)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:665)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:660)
	at edu.usf.cutr.gtfsrtvalidator.helper.DBHelper.saveError(DBHelper.java:33)
	at edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask.validateEntity(BackgroundTask.java:258)
	at edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask.run(BackgroundTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLDataException: data exception: string data, right truncation;  table: OCCURRENCE column: PREFIX
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
	... 31 more
Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation;  table: OCCURRENCE column: PREFIX
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Table.enforceTypeLimits(Unknown Source)
	at org.hsqldb.Table.generateAndCheckData(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertRowSet(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 34 more
Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.types.CharacterType.convertToTypeLimits(Unknown Source)
	... 42 more
~~~

**Steps to reproduce:** 

Run the project in normal server mode and input the following RATP's feeds:
* GTFS - http://ratp.spiralo.net/stif_gtfs_enhanced_rer_latest.zip
* GTFS-realtime Trip Updates - http://stif.spiralo.net/STIF

**Expected behavior:** 

Validate the feeds without any exceptions

**Observed behavior:** 

HsqlException above occurs

**Platform:** 

Windows 7 Enterprise SP1 with jdk1.8.0_73 and Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by barbeau** [comment]
Looks like updating to the newest HSQLDB version fixes this:

~~~
<dependency>
	<groupId>org.hsqldb</groupId>
	<artifactId>hsqldb</artifactId>
	<version>2.4.0</version>
</dependency>
~~~

**Comment by barbeau** [comment]
I'm seeing this again, re-opening...

**Comment by barbeau** [comment]
So this error was originally ticketed in https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/173.  To fix it there I just increased the column size, but obviously that doesn't work in all cases.

**Comment by barbeau** [comment]
The issue here seems to be that the `stop_id` fields for this feed are long:
`StopPoint:8738188:800:J`

For errors like E002, the prefix includes all `stop_ids` that are out-of-order when the `stop_sequence` isn't provided.  This ends up being a long list, and with the long `stop_ids` it ends up exceeding the column width.

**Comment by barbeau** [comment]
Here's an example prefix for E002:

~~~
trip_id 86061259-199897 stop_sequence for stop_ids [StopPoint:6:306, STIF:StopPoint:Q:2187:, StopPoint:88:243, StopPoint:6:283, StopPoint:6:279, StopPoint:6:81, StopPoint:6:84, StopPoint:6:54, StopPoint:6:46, StopPoint:6:52, StopPoint:6:30, StopPoint:6:26, StopPoint:6:39, StopPoint:6:37, StopPoint:6:32, STIF:StopPoint:Q:426792:, StopPoint:6:178, StopPoint:6:180, StopPoint:6:174, StopPoint:6:176]
--




trip_id 86061259-199897 stop_sequence for stop_ids [StopPoint:6:306, STIF:StopPoint:Q:2187:, StopPoint:88:243, StopPoint:6:283, StopPoint:6:279, StopPoint:6:81, StopPoint:6:84, StopPoint:6:54, StopPoint:6:46, StopPoint:6:52, StopPoint:6:30, StopPoint:6:26, StopPoint:6:39, StopPoint:6:37, StopPoint:6:32, STIF:StopPoint:Q:426792:, StopPoint:6:178, StopPoint:6:180, StopPoint:6:174, StopPoint:6:176]
--
