### ISSUE TITLE
Failed Travis build after implementing submodules

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#305]
**Summary:** 

[This Travis build](https://travis-ci.org/CUTR-at-USF/gtfs-realtime-validator/builds/295854536) has this error:

~~~
[main] ERROR edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeed - Downloading GTFS Feed Failed
java.io.FileNotFoundException: https://github.com/CUTR-at-USF/gtfs-realtime-validator/raw/master/src/test/resources/bullrunner-gtfs.zip
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeed.downloadGtfsFeed(GtfsFeed.java:314)
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeed.postGtfsFeed(GtfsFeed.java:133)
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest.testGtfsFeed(GtfsFeedTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: java.io.FileNotFoundException: https://github.com/CUTR-at-USF/gtfs-realtime-validator/raw/master/src/test/resources/bullrunner-gtfs.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:291)
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeed.downloadGtfsFeed(GtfsFeed.java:305)
~~~

Looks like a unit test is hard-coded to fetch the zip file from the live Github repo, and we just changed the folder path.

**Steps to reproduce:** 

Run unit tests (above, on Travis), for example:

`mvn package`

**Expected behavior:** 

Tests pass and project builds

**Observed behavior:** 

Unit test fails with the above error

**Platform:** 

Travis build https://travis-ci.org/CUTR-at-USF/gtfs-realtime-validator/builds/295854536.

**Comment by barbeau** [comment]
Ack - re-opening - I probably should have actually tested the URLs first...
