### ISSUE TITLE
Can't load GTFS data from an URL

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#62]
When running the application, it won't load GTFS data from the provided URL.

### Steps to reproduce:

1. Clone `master` branch
1. Run the application
1. Enter a GTFS URL to the GTFS zip file

Reported by @scrudden.  @scrudden let me know if I got any of the above incorrect.

@mohangandhiGH Could you please take a look at this?

**Comment by barbeau** [comment]
@scrudden what URL did you use?  I just fired it up and used http://gohart.org/google/google_transit.zip and it seemed to download successfully.

**Comment by mohangandhiGH** [comment]
When http://gohart.org/google/google_transit.zip is used, it downloaded successfully with no feed errors.

But looks like there is feed error when tried with http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip

Here is the stack trace
WARNING:
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.ClassFormatError: Invalid superclass index 0 in class file com/conveyal/gtfs/service/impl/GtfsStatisticsService
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:423)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
        at java.lang.Thread.run(Unknown Source)

@scrudden Is this the URL you also tried with?

**Comment by scrudden** [comment]
I tried from my public drop box and one from my google drive.

https://dl.dropboxusercontent.com/u/107527881/final_dt2.zip

https://drive.google.com/file/d/0BzTMCDngWQJ4eElfWV9tZE1vRUU/view?usp=sharing

**Comment by mohangandhiGH** [comment]
@scrudden  could you please provide a download Url for final_dt2.zip  file in https://drive.google.com/file/d/0BzTMCDngWQJ4eElfWV9tZE1vRUU/view?usp=sharing

**Comment by mohangandhiGH** [comment]
@scrudden I tried to generate direct download link for https://drive.google.com/file/d/0BzTMCDngWQJ4eElfWV9tZE1vRUU/view?usp=sharing using the website [https://sites.google.com/site/gdocs2direct/](https://sites.google.com/site/gdocs2direct/)

Here is the download link
https://drive.google.com/uc?export=download&id=0BzTMCDngWQJ4eElfWV9tZE1vRUU

Could you please use this link after the issue is fixed.
